test_that("test-GRIDobj checks whether each case silently creates a GRIDobj without errots and whether provided properties are preserved.", {
  # Case 1: GRIDobj(NULL)
  expect_no_error(GRIDobj(NULL))
  expect_no_message(GRIDobj(NULL))
  expect_true(inherits(GRIDobj(NULL), "GRIDobj"))
  # Case 2: GRIDobj("path/to/file") - no test yet
  # Case 3: GRIDobj(SpatRaster)
  funnel <- t(matrix(1,5,5)*c(3,2,1,2,3))*c(3,2,1,2,3)
  funnel[funnel > 6] <- 6
  slope <- t(matrix(6,5,5) + c(1,2,3,4,5)) + c(2,1,0,1,2) - 2
  m <- cbind(funnel, slope)
  crs <- "EPSG:25833"
  DEMr <- terra::rast(m, crs=crs)
  expect_no_error(GRIDobj(DEMr))
  expect_no_message(GRIDobj(DEMr))
  expect_true(inherits(GRIDobj(DEMr), "GRIDobj"))
  # Case 4.1: GRIDobj(Z)
  expect_no_error(DEM <- GRIDobj(m))
  expect_no_message(GRIDobj(m))
  expect_true(inherits(GRIDobj(m), "GRIDobj"))
  expect_true(all(m == matrix(terra::values(DEM$raster), 5, 10, byrow=T)))
  # Case 4.2: GRIDobj(Z, cs)
  cs <- 2
  expect_no_error(DEM <- GRIDobj(m, cs))
  expect_no_message(GRIDobj(m, cs))
  expect_true(inherits(GRIDobj(m,cs), "GRIDobj"))
  expect_true(all(terra::res(DEM$raster) == cs))
  # Case 4.3: GRIDobj(Z, cs, crs)
  expect_no_error(DEM <- GRIDobj(m, cs, crs))
  expect_no_message(GRIDobj(m, cs, crs))
  expect_true(inherits(GRIDobj(m, cs, crs), "GRIDobj"))
  expect_true(identical(terra::crs(DEMr), terra::crs(DEM$raster)))
  # Case 4.4: GRIDobj(Z, x, y)
  x <- 2:(dim(m)[2]+1)
  y <- 3:(dim(m)[1]+2)
  expect_no_error(DEM <- GRIDobj(m, x, y))
  expect_no_message(GRIDobj(m, x, y))
  expect_true(inherits(GRIDobj(m, x, y), "GRIDobj"))
  # Case 5.1: GRIDobj(TTobj)
  expect_no_error(DEMg <- GRIDobj(DEM))
  expect_no_message(GRIDobj(DEM))
  expect_true(inherits(GRIDobj(DEM), "GRIDobj"))
  expect_true(all(get_values(DEMg) == 0))
  # Case 5.2: GRIDobj(TTobj, 'class')
  expect_true(is.integer(get_values(GRIDobj(DEM, "integer"))))
  expect_true(is.double(get_values(GRIDobj(DEM, "double"))))
  expect_true(is.logical(get_values(GRIDobj(DEM, "logical"))))
  # Case 5.3: GRIDobj(TTobj, Z)
  expect_error(GRIDobj(GRIDobj(DEMr), t(m)))
})